-- USER TABLE
create table TABLE_USER(OBJID INT PRIMARY KEY, USER_ID VARCHAR(50),USER_NAME VARCHAR(50),ADDRESS VARCHAR(255),PHONE VARCHAR(20),STATUS CHAR,CREATE_DATE DATE,USER_TYPE VARCHAR(20));

insert into table_user values(1000,'Raju123','Raju Rawat','NA','09557022303','A',sysdate,'Admin_User');
select * from table_user;

-- CREDENTIALS TABLE
CREATE TABLE CRED_TBL(OBJID INT PRIMARY KEY, USER_ID VARCHAR(20),PASSWORD VARCHAR(20));

INSERT INTO CRED_TBL VALUES(2000,'RAJU123','Raju@123');

select * from CRED_TBL;

-- PRODUCT TABLE

CREATE TABLE PRODUCT_TBL(OBJID INT PRIMARY KEY, PROD_ID VARCHAR(20), PROD_DESC VARCHAR(20), GST INT, OTHER_PRODUCT_CODE VARCHAR(20), OTHER_PRODUCT_DETAILS VARCHAR(250), PRODUCT_TYPE VARCHAR(20),STATUS CHAR, EFFECTIVE_DATE DATE);

INSERT INTO PRODUCT_TBL VALUES(3000,'100000','Product_1',450,'20000','NA','NA','A',sysdate);

select * from PRODUCT_TBL;

-- CUSTOMER TABLE
CREATE TABLE CUSTOMER_TBL(OBJID INT PRIMARY KEY, CUSTOMER_ID VARCHAR(20), CUSTOMER_NAME VARCHAR(20), ADDRESS VARCHAR(250), PHONE_NUMBER VARCHAR(15), GST VARCHAR(25),
PAN_NUMBER VARCHAR(25), CUSTOMER_SPOC VARCHAR(20), STATE INT, STATUS CHAR, START_DATE DATE);

INSERT INTO CUSTOMER_TBL VALUES(4000,'100000','CUSTOMER_1','NA','9557022303','18%','AVPUR355R','NA',5000,'A',sysdate);

select * from CUSTOMER_TBL;

-- STATE TABLE

CREATE TABLE STATE_TBL(OBJID INT PRIMARY KEY , STATE VARCHAR(50));

INSERT INTO STATE_TBL VALUES(5000,'KARNATAKA');

SELECT * FROM STATE_TBL;